# Generated by Django 3.0.6 on 2020-05-12 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_a', models.CharField(db_column='party_A', max_length=512)),
                ('party_b', models.CharField(db_column='party_B', max_length=512)),
                ('party_c', models.CharField(db_column='party_C', max_length=512)),
            ],
        ),
    ]
