# Generated by Django 3.0.6 on 2020-05-12 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='party',
            table='party',
        ),
    ]
